name: Football
version: 2.0.0
api: 4.0.0
main: matze\football\Football
author: Matze
mcpe-protocol: [475]

permissions:
  football.use:
    default: op
    description: Allow players to use the football command
  football.spawn:
    default: op
    description: Allow players to spawn footballs
  football.remove:
    default: op
    description: Allow players to remove all footballs
